---
title: "Quick start guide"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

You have come to the right place! Here, we go over what you need to know to process your data and visualize a given dataset. The information herein is organized according to the tabs on this data viewer: “Data”, “Report”, “Plot”, “Interactive Plot”, “Code”, "About".

If you do not find the answer you are looking for on this page, please visit the “About” tab and refer to the package/viewer contacts.

### Data:

Data loading options:

* Use sample data: Sample data automatically loaded when `datapie` opens.
* Fetch data from DOI: The Digital Object Identifier (DOI) of any data package available in the [DataONE search portal](https://search.dataone.org/data), well almost. Only tables are currently supported. Other data types will be supported in the future.
* Upload data: Upload a file from your computer. (Coming soon!)

How it works:

On the left side of the application are three options:
“Load sample data”, “Fetch data from DOI”, or “Upload text file”.

Load sample data - allows a user to download the example dataset provided.

Fetch Data from DOI - a user enters a given DOI (Digital object identifier) and clicks “Fetch Data”.

Upload text file - by clicking “Browse” one can find and upload one of five file types: text (csv), Excel, SPSS, Strata, or SAS. Then select the delimiter (how the data is formatted within that file) based upon four options: Semicolon, Tab, Comma, or Space. Select “Submit datafile” and the data file will appear on the right. If your uploaded datafile does not appear the way you wish, you may need to create a copy of the file and edit headers or delete rows in the top of the document that may contain study information, of which is important, however this application is not designed to know how many rows to skip in any one dataset. The columns at the top of the page are from the top row of the document uploaded.

One can expand or decrease the amount of rows shown on a given page with the options of 10, 25, 50 and 100.

Summary Report:

Based upon the data uploaded, click “Generate report”. On the right side of the page a summary report of the provided data will be appear.

The summary report will display a brief snippet of a given data table within the data package. This report provides general table-level information such as number of observations and NA’s per variable, min, max, mean, 1st quartile and 3rd quartiles for numeric variables and number of levels and distribution of levels for categorical variables. REVIEW TO MAKE SURE CORRECT… This report is limited to XXXXX variables.

Please note some reports can take some time to be generated. The web interface will indicate the progression of the generation of the report. - IS THIS CORRECT?

The processing for this report identifies several different formats of geographic coordinates and several different formats of dates/times. Please note that not all formats will be recognized.

If you are satisfied with the generated report, click “Download report (HTML)”. This HTML can be saved or printed to PDF. Images within the HTML can saved individually by the user.

Plot:

This portion of the application allows the user to create and edit plots in an easy to use format with the option to save the plot created.

In the central portion of the page, a static plot is generated. On the left side of the page, the user can select the type of plot (boxplot, histogram, scatter) and the x and y variables.

Based upon what plot is selected, the user can choose between a variety of options. EXPLAIN OPTIONS IN MORE DETAIL…..

On the right side of the page the user is given the option to change the aesthetics of the plot. Tabs shown are: “Text”, “Theme”, “Legend”, and “Size”. Here the labels on the graph’s axes can be changed, a title may be added, font sizes can be adjusted, text can be rotated, colors selected, gridlines removed, legend edited, and the size of chart adjusted.

The user is given the option to download a pdf or tiff file format of the figure.

Interactive Plot:

The interactive plot gives the user the same options as the plot, however is different in that….. XXXXXXXXXXXXXXX

Please note datasets with greater than 100,000 points will take longer to plot and should be avoided by users. We recommend dividing up your datasets if this is the case.

R-code:

The R-code is enclosed for the purpose of XXXXXXXXXXXXXXXXXXXX