---
title: "`r report_title`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
---

```{r echo = F}
knitr::opts_chunk$set(comment=NA, echo = F, message = F, warning = F, out.width = '100%', fig.height = 3)
```

---

&nbsp;

## Overall Data Table Report 

&nbsp;

#### Column-wise: numerical variables

```{r echo=FALSE}
if (length(entity_report[["numvars"]]) > 0) {
kable(as.data.frame(entity_report[["numvars"]]))
} else {
  print("No numerical variables found.")
}
```

&nbsp;

#### Column-wise: Categorical and character variables

```{r}
if (length(entity_report[["catvars"]]) > 0) {
kable(entity_report[["catvars"]])
} else {
  print("No categorical/character variables found.")
}
```

&nbsp;

#### Column-wise: Levels in Categorical and character variables

```{r}
if (length(entity_report[["levels"]]) > 0) {
kable(entity_report[["levels"]])
} else {
  print("No categorical/character variables found.")
}
```

&nbsp;

---

## Temporal information


---

## Spatial information

```{r}
xy <- space_detective(entity_list)
```


---

&nbsp;

## Variable-by-variable Report

```{r results='asis'}
for (i in 1:length(var_report)) {
   cat('\n')
   cat('\n')
   cat(paste("### Variable:", var_report[[i]][["var_name"]]))
   cat('\n')
   print(var_report[[i]][["plots"]][["x"]])
   cat('\n')
   if (!is.null(var_report[[i]][["missing"]])) {
      print(var_report[[i]][["missing"]])
      cat('\n')
   }
   if (!is.null(var_report[[i]][["space"]])) {
      print(var_report[[i]][["space"]][[1]])
      cat('\n')
      print(var_report[[i]][["space"]][[2]])
      cat('\n')
   }
}
```